language: rust
os:
  - linux
cache:
  directories:
    - target
    - ~/.cargo/bin
deploy:
  api_key: $GITHUB_OAUTH_TOKEN
  file: index.html
  provider: releases
  skip_cleanup: true
  true:
    tags: false
script:
  - "cargo test --release"
  - "rustup target add wasm32-unknown-unknown"
  - "cargo install cargo-make||true"
  - "sudo apt-get install npm"
  - "npm install terser -g"
  - "sh build.sh"
