cache: 
  directories: 
    - binaryen
    - target
jobs: 
  include: 
    - 
      deploy: 
        api_key: $GITHUB_OAUTH_TOKEN
        file: index.html
        provider: releases
        skip_cleanup: true
        true: 
          tags: false
      script: 
        - "rustup target add wasm32-unknown-unknown"
        - "cargo install --force cargo-make"
        - "sudo apt-get install npm cmake"
        - "cd binaryen && git pull || cd && git clone --depth=1 https://github.com/WebAssembly/binaryen"
        - "cd binaryen && cmake . && ccache make && sudo ccache make install && cd ../"
        - "npm install terser -g"
        - "sh build.sh"
      stage: build_and_deploy
language: rust
os: 
  - linux
rust: 
  - stable
  - beta
  - nightly
stages: 
  - build_and_test
