language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
cache:
  - cargo
  - ccache 
jobs:
  include:
    - stage: dependencies
      script:
        - rustup target add wasm32-unknown-unknown
        - cargo install --force cargo-make
        - sudo apt-get install npm cmake
        - npm install terser -g
        - git clone --depth=1 https://github.com/WebAssembly/binaryen && cd binaryen && cmake . && ccache make
      rust: stable
    - stage: build_and_test
      script:
        - alias wasm-opt=binaryen/bin/wasm-opt
        - sh build.sh
        - cargo test --release --verbose
      
