language: rust
os:
  - linux
cache:
  directories:
    - binaryen
    - target
    - ~/.cargo/bin
deploy:
  api_key: $GITHUB_OAUTH_TOKEN
  file: index.html
  provider: releases
  skip_cleanup: true
  true:
    tags: false
script:
  - "cargo test --release"
  - "rustup target add wasm32-unknown-unknown"
  - "cargo install cargo-make||true"
  - "sudo apt update"
  - "sudo apt-get install npm cmake gcc g++"
  - "git clone --depth=1 https://github.com/WebAssembly/binaryen||(cd binaryen; git pull; cd ../)"
  - "cd binaryen && cmake . && make && sudo make install && cd ../"
  - "npm install terser -g"
  - "sh build.sh"
