language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
matrix:
  fast_finish: true
cache: cargo
script:
  - rustup target add wasm32-unknown-unknown
  - cargo install --force cargo-make
  - sudo apt-get install binaryen npm -y
  - npm install terser -g
  - ./build.sh
  - cargo test --release --verbose
