[package]
name = "social_schedule"
version = "0.1.0"
authors = ["Hugh Williams <hughaw64@gmail.com>"]

[dependencies]
rand = "0.4"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
